# Generated by Django 6.0.3 on 2026-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('trust', 'Trust / NGO'), ('semi-govt', 'Semi-Government')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='hospital_documents/'),
        ),
    ]
